Repository debasishray16/StockPredictor, pull requests merged in 2024-11, with the labels that each got.

#49 Model: 300 Epoch added
  site_integration/backend/__pycache__/backend_API.cpython-312.pyc
  site_integration/backend/backend_API.py
  site_integration/model/8_15_23_300_LXg.h5
  site_integration/src/Components/Dashboardview.js
  site_integration/src/Components/Main.js
  site_integration/src/Components/Sidebar.js
  site_integration/src/Components/StockPredictionChart.js
  site_integration/src/Components/companyInfo.js
Labels: enhancement

#51 Update: Button fixed and some tweaks
  Ticker Predictor Website/Back-end/__pycache__/model_api.cpython-312.pyc
  Ticker Predictor Website/Front-end/src/App.js
  Ticker Predictor Website/Front-end/src/Components/Dashboardview.js
  Ticker Predictor Website/Front-end/src/Components/Main.js
  Ticker Predictor Website/Front-end/src/Components/Sidebar.js
  Ticker Predictor Website/Front-end/src/Components/Spinner.js
  Ticker Predictor Website/Front-end/src/Components/StockPredictionChart.js
  Ticker Predictor Website/Front-end/src/Components/Styles/spinner.css
  Ticker Predictor Website/Front-end/src/Components/companyDesc.js
  Ticker Predictor Website/Front-end/src/Components/companyInfo.js
  Ticker Predictor Website/Front-end/src/assets/idle.gif
  Ticker Predictor Website/Front-end/src/assets/loading.gif
  Ticker Predictor Website/Front-end/src/assets/loading2.gif
  Ticker Predictor Website/Front-end/src/index.css
  Ticker Predictor Website/Front-end/src/router/Router.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: bug

#52 Feature debasish
  README.md
  Ticker Predictor Streamlit/8_15_23_125_LXg.h5
  Ticker Predictor Streamlit/Dockerfile
  Ticker Predictor Streamlit/__pycache__/nasdaq_list.cpython-312.pyc
  Ticker Predictor Streamlit/app.py
  Ticker Predictor Streamlit/nasdaq.csv
  Ticker Predictor Streamlit/nasdaq_list.py
  Ticker Predictor Streamlit/requirements.txt
  Ticker Predictor Website/Back-end/.dockerignore
  Ticker Predictor Website/Back-end/Dockerfile
  Ticker Predictor Website/Back-end/requirements.txt
  Ticker Predictor Website/Front-end/.dockerignore
  Ticker Predictor Website/Front-end/Dockerfile
  Ticker Predictor Website/Front-end/package-lock.json
  Ticker Predictor Website/Front-end/package.json
  docker-compose.yml
Labels: documentation, enhancement
